# Pipeline Bag of Words

In [2]:
import class_nlp_preprocess as nlppreprocess

obj_nlprepro = nlppreprocess.class_train_model()

In [5]:
# Cria o dataframe inicial com os comentários raspados
df = obj_nlprepro.read_df_file()

# Faz o preprocessamento da base para iniciar vetorização e tokenização
df_final = obj_nlprepro.preprocess_data(df, 
                                        columns = ['COMMENT_TEXT', 'RATING_VALUE'],
                                        label_column='RATING_VALUE', 
                                        null = True,
                                        labels_ok = False,
                                        dict_labels = {(' '): '', (','): '.'},
                                        labels_ready = False, 
                                        labels_true = {(5,5): 2, (4,4):0,(1,2,3):1}
                                       )

# contruindo a coluna nova com os sentimentos
df_final['sentimentos'] = df_final['RATING_VALUE'].apply(obj_nlprepro.sentimento)

# Faz o balanço das classes
df_final = obj_nlprepro.balance_classes(df_final)

# tokenização
df_final = obj_nlprepro.tokenizacao(df_final)

# cria a lista de treino com as palavras para o modelo
lista_treino = obj_nlprepro.treinar_vetorizacao(df_final)

# criando a coluna com o texto vetorizado
df_final['vectors'] = df_final['token'].apply(obj_nlprepro.vectorize2)

# cria o dicionário para o bag of words
df_final['dic_bag'] = df_final['token'].apply(obj_nlprepro.dic_bag_of_worlds)

# cria a bag of words
df_dic_bag = obj_nlprepro.df_dic_bag(df_final,'token')

C:\Users\osval\Google Drive\Meu Drive\14 Historico_Profissional\14 KLB_Samsung\05 Bag of Words\class_nlp_preprocess.py:57: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df1.append(df2).reset_index().drop(columns=['index'])

In [8]:
df_dic_bag

         Palavra  Quantidade
0            bom        6522
1        produto        4341
2        celular        3006
3           timo        2813
4        bateria        2479
...          ...         ...
9934     cativou           1
9935       lance           1
9936    gargalos           1
9937  registrado           1
9938      cupons           1

[9939 rows x 2 columns]

In [6]:
df_final

,COMMENT_TEXT,RATING_VALUE,sentimentos,token,vectors,dic_bag
0,"Gostando, corresponde ao que imaginei...só est...",5.0,2,"[gostando, corresponde, imaginei, tendo, probl...","[4441, 2173, 4691, 9081, 7499, 9324, 2338, 963...","{'gostando': 1, 'corresponde': 1, 'imaginei': ..."
1,Produto bom.,5.0,2,"[produto, bom]","[7544, 1241]","{'produto': 1, 'bom': 1}"
2,"É bom, dentro do que foi prometido.",5.0,2,"[bom, dentro, prometido]","[1241, 2515, 7575]","{'bom': 1, 'dentro': 1, 'prometido': 1}"
3,Muito bom,5.0,2,[bom],[1241],{'bom': 1}
4,Bom pelo valor atendeu minhas expectativas.\r\n,5.0,2,"[bom, valor, atendeu, expectativas]","[1241, 9596, 855, 3772]","{'bom': 1, 'valor': 1, 'atendeu': 1, 'expectat..."
...,...,...,...,...,...,...
19368,Celular deveria vir limpo a cada um coloca o q...,3.0,1,"[celular, deveria, vir, limpo, cada, coloca, q...","[1541, 2798, 9758, 5332, 1355, 1756, 7737, 617...","{'celular': 1, 'deveria': 1, 'vir': 1, 'limpo'..."
19369,"Gostei muito do produto, cumpre minhas expecta...",4.0,0,"[gostei, produto, cumpre, expectativas, bateri...","[4450, 7544, 2290, 3772, 1110, 3703]","{'gostei': 1, 'produto': 1, 'cumpre': 1, 'expe..."
19370,"Não sei se é só o meu, mas a cor da tela é est...",4.0,0,"[sei, cor, tela, estranha, parece, tela, origi...","[8501, 2155, 9044, 3622, 6840, 9044, 6699]","{'sei': 1, 'cor': 1, 'tela': 2, 'estranha': 1,..."
19371,Excelente produto!,4.0,0,"[excelente, produto]","[3703, 7544]","{'excelente': 1, 'produto': 1}"
19372,"Bom, a bateria dura bastante",4.0,0,"[bom, bateria, dura, bastante]","[1241, 1110, 3057, 1101]","{'bom': 1, 'bateria': 1, 'dura': 1, 'bastante'..."

In [7]:
df_dic_bag.head()

   Palavra  Quantidade
0      bom        6522
1  produto        4341
2  celular        3006
3     timo        2813
4  bateria        2479